version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: nikolay
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diploma_db
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
      build: .
      container_name: my_fastapi_app
      depends_on:
        - postgres
      environment:
        - DATABASE_URL=postgresql+asyncpg://nikolay:1234@postgres:5432/diploma_db
      ports:
        - "8000:8000"
      volumes:
        - ./app:/api/app
        - ./database:/api/database
        - ./pictures:/api/pictures
        - ./config.py:/api/config.py
        - ./.env:/api/.env
        - ./main.py:/api/main.py
  nginx:
    image: nginx:latest
    container_name: my_nginx
    depends_on:
      - app
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf
      - ./static:/api/static
      - ./pictures:/api/pictures
    restart: always